# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: fleetms-service
spec:
  ports:
    - protocol: "TCP"
      port: 8081    
      targetPort: 8081  
  selector:
    app: fleetms-v2
  type: NodePort

---

# Define a 'Service' To Expose MySQL to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None 