apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetms-v2
spec:
  selector:
    matchLabels:
      app: fleetms-v2
  replicas: 3
  template:
    metadata:
      labels:
        app: fleetms-v2
    spec:
      containers:
        - name: fleetms-v2
          image: shashwatknol/finalcapestone:v1
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: fleetdb
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
